import type { Config } from "tailwindcss";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* new vars */
        brand:          "var(--brand)",
        "brand-2":      "var(--brand-2)",
        "brand-hover":  "var(--brand-hover)",
        "brand-light":  "var(--brand-light)",
        "brand-mid":    "var(--brand-mid)",
        surface:        "var(--surface)",
        bg:             "var(--bg)",
        bg2:            "var(--bg2)",
        bg3:            "var(--bg3)",
        brd:            "var(--brd)",
        brd2:           "var(--brd2)",
        tx1:            "var(--tx1)",
        tx2:            "var(--tx2)",
        tx3:            "var(--tx3)",
        tx4:            "var(--tx4)",
        ok:             "var(--ok)",
        err:            "var(--err)",
        /* ALL legacy aliases so old pages still work */
        navy:           "var(--navy)",
        navy2:          "var(--navy2)",
        navy3:          "var(--brand-hover)",
        mint:           "var(--brand-light)",
        mint2:          "var(--brand-mid)",
        gold:           "var(--brand)",
        teal:           "var(--brand)",
        teal2:          "var(--brand-2)",
        ceil:           "var(--brand)",
        "ceil-soft":    "var(--brand-light)",
        "ceil-mid":     "var(--brand-mid)",
        primary:        "var(--brand-light)",
        "primary-light":"var(--brand-light)",
        "primary-dark": "var(--brand-hover)",
        secondary:      "var(--brand-hover)",
        accent:         "var(--brand-2)",
        "text-primary":   "var(--tx1)",
        "text-secondary": "var(--tx2)",
        "text-muted":     "var(--tx3)",
        "surface-2":      "var(--surface2)",
        "surface-3":      "var(--surface3)",
        "border-dark":    "var(--brd2)",
        border:           "var(--brd)",
        warning:          "var(--warn)",
        success:          "var(--ok)",
        danger:           "var(--err)",
        error:            "var(--err)",
      },
      fontFamily: { sans: ["Tajawal", "sans-serif"] },
      blur: { "120px": "120px", "100px": "100px" },
    },
  },
  plugins: [],
};
export default config;
